"""empty message

Revision ID: 0aaa2ac4bc7f
Revises: c40b4a683fe9
Create Date: 2025-08-15 15:38:38.967300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaa2ac4bc7f'
down_revision = 'c40b4a683fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_detail', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('request_detail_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'request', ['request_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('request_detail_ibfk_2'), 'request', ['request_id'], ['id'])

    # ### end Alembic commands ###
