"""empty message

Revision ID: 10e52a6d0429
Revises: a79078a84b05
Create Date: 2025-07-21 15:14:31.309694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10e52a6d0429'
down_revision = 'a79078a84b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('return_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
