"""empty message

Revision ID: 3044be016a6a
Revises: 10e52a6d0429
Create Date: 2025-07-21 15:23:21.703561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3044be016a6a'
down_revision = '10e52a6d0429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RETURNED', name='statuscheck'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RETURNED', name='statuscheck'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
