"""empty message

Revision ID: 50399aa674cd
Revises: 49971d8bfc7d
Create Date: 2025-07-11 11:23:25.074370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50399aa674cd'
down_revision = '49971d8bfc7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
