"""empty message

Revision ID: 6f98c403aec4
Revises: 08baeebed1d5
Create Date: 2025-07-10 08:42:57.614152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f98c403aec4'
down_revision = '08baeebed1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'LIBRARIAN', 'READER', collation='utf8mb4_unicode_ci'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'LIBRARIAN', 'READER', collation='utf8mb4_unicode_ci'),
               nullable=False)

    # ### end Alembic commands ###
