"""empty message

Revision ID: 9043d23750ea
Revises: 0aaa2ac4bc7f
Create Date: 2025-08-15 15:42:53.163013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9043d23750ea'
down_revision = '0aaa2ac4bc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('published_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('published_date')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
