"""empty message

Revision ID: 97a1dcfb711c
Revises: 3044be016a6a
Create Date: 2025-07-21 15:34:57.502481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97a1dcfb711c'
down_revision = '3044be016a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
