"""empty message

Revision ID: a8ecbf6b1cf8
Revises: e292dcaabf17
Create Date: 2025-08-15 14:15:10.555185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8ecbf6b1cf8'
down_revision = 'e292dcaabf17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('cccd', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('job', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ward', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('ward')
        batch_op.drop_column('city')
        batch_op.drop_column('phone')
        batch_op.drop_column('cccd')
        batch_op.drop_column('province')
        batch_op.drop_column('job')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('province', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('cccd', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True))
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('ward', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True))

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('province')
        batch_op.drop_column('ward')
        batch_op.drop_column('address')
        batch_op.drop_column('job')
        batch_op.drop_column('cccd')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
