"""empty message

Revision ID: ad672794c5f7
Revises: bcc99195398a
Create Date: 2025-07-18 11:48:48.201685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad672794c5f7'
down_revision = 'bcc99195398a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('average_rating',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('average_rating',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
