"""empty message

Revision ID: bcc99195398a
Revises: 0e24d23340c9
Create Date: 2025-07-18 11:43:02.408248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bcc99195398a'
down_revision = '0e24d23340c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('average_rating',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('average_rating',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
