"""empty message

Revision ID: dcc560db1e38
Revises: bae52bdb3126
Create Date: 2025-08-15 13:38:03.156721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc560db1e38'
down_revision = 'bae52bdb3126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relative',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_requests_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('borrowing_method', sa.Enum('DIRECT', 'TRANSPORT', name='borrowingmethod'), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('cccd', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('job', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ward', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('province', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'RETURNED', name='statuscheck'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('city')
        batch_op.drop_column('province')
        batch_op.drop_column('ward')
        batch_op.drop_column('address')
        batch_op.drop_column('job')
        batch_op.drop_column('cccd')
        batch_op.drop_column('phone')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('purpose')
        batch_op.drop_column('borrowing_method')
        batch_op.drop_column('number_of_requests_day')

    op.drop_table('relative')
    # ### end Alembic commands ###
