"""empty message

Revision ID: e292dcaabf17
Revises: dcc560db1e38
Create Date: 2025-08-15 13:39:32.809586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e292dcaabf17'
down_revision = 'dcc560db1e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'RETURNED', collation='utf8mb4_unicode_ci'), nullable=False))

    # ### end Alembic commands ###
