"""empty message

Revision ID: f30f050ef1a2
Revises: 97a1dcfb711c
Create Date: 2025-07-21 19:30:39.068571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30f050ef1a2'
down_revision = '97a1dcfb711c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('librarian_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['librarian_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('librarian_id')

    # ### end Alembic commands ###
